spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true

com:
  rxvlvxr:
    bank:
      jwtSecret: SECRET
      jwtExpiration: 3600